Update gridai_session.yml

diff --git a/.github/workflows/gridai_session.yml b/.github/workflows/gridai_session.yml
--- a/.github/workflows/gridai_session.yml
+++ b/.github/workflows/gridai_session.yml
@@ -54,3 +54,49 @@ jobs:
           grid ssh-keys add lit_key ~/.ssh/id_ed25519.pub
       - run: |
           grid session ssh ${SESSION_NAME} "ls; exit"
+      - run: |
+          grid session pause ${SESSION_NAME}
+      - run: |
+          SESSION_STATUS=$(grid session | grep " ${SESSION_NAME} " | awk '{print $4}')
+          # pool at 1 min interval
+          while [ "${SESSION_STATUS}" != 'paused' ]; do 
+            echo "${SESSION_NAME}:${SESSION_STATUS} waiting 60 sec for the next status"
+            sleep 60 
+            SESSION_STATUS=$(grid session | grep " ${SESSION_NAME} " | awk '{print $4}')
+          done
+          case ${SESSION_STATUS} in
+            paused)
+              ;;
+            *)
+              echo "Error: ${SESSION_NAME} did not pause"
+              exit 1
+          esac
+      - run: |
+          grid session resume ${SESSION_NAME}
+      - run: |
+          SESSION_STATUS=$(grid session | grep " ${SESSION_NAME} " | awk '{print $4}')
+          # pool at 1 min interval
+          while [ "${SESSION_STATUS}" != 'running' ]; do 
+            echo "${SESSION_NAME}:${SESSION_STATUS} waiting 60 sec for the next status"
+            sleep 60 
+            SESSION_STATUS=$(grid session | grep " ${SESSION_NAME} " | awk '{print $4}')
+          done
+          case ${SESSION_STATUS} in
+            running)
+              ;;
+            *)
+              echo "Error: ${SESSION_NAME} did not resume"
+              exit 1
+          esac    
+      - run: |
+          grid session ssh ${SESSION_NAME} "ls; exit"                            
+      - run: |
+          grid session delete ${SESSION_NAME}
+      - run: |
+          SESSION_STATUS=$(grid session | grep " ${SESSION_NAME} " | awk '{print $4}')
+          # pool at 1 min interval
+          while [ -z "${SESSION_STATUS}" ]; do 
+            echo "${SESSION_NAME}:${SESSION_STATUS} waiting 60 sec for the next status"
+            sleep 60 
+            SESSION_STATUS=$(grid session | grep " ${SESSION_NAME} " | awk '{print $4}')
+          done           
